services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      OPENROUTER_API_KEY: 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
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  frontend_node_modules: {}
  mongo_data: {}
